### ISSUE TITLE
Draggable block: mouse-up unregistered.

### ISSUE THREAD

**Issue by redbearsam** [Syreniac/verdant-octo-spork#17]
If you're dragging the block when you move out of the expanded block it plays in, when you move back inside, the mouse is registered as still held down. This is minutia, but clearly we want it dropped either when

a) you move out of bounds.

or b) when you release the mouse button.

One of these. I'll play with it a bit tonight.

**Comment by Syreniac** [comment]
I think this was fixed at some point so that the draggable block will still be picked up until someone lets go of the mouse, but will behave itself and sit inside it's parent's rectangle. This behaviour to me seems more like 'normal' UI stuff, but I'm willing to work around it if we need.
