### ISSUE TITLE
Windows makefile is broken

### ISSUE THREAD

**Issue by Syreniac** [Syreniac/verdant-octo-spork#19]
The windows makefile is missing several parts that are required to get it to compile.

E.g. adding -lSDL_image to the LFLAGS.

**Comment by shirakaba** [comment]
Working on it, need some more sleep and a few more hours to get it all going automatically, but it works for Win64 and Mac if you pull in copies of the SDL_Image .dlls and SDL2.dll straight into the bin folder. For Windows, the directory should end up looking like below after running the makefile for Win64. For the lab machines, we need to find the Linux version of SDL_Image and tweak the makefile to link the necessary files in. For Mac, it just all works without a problem anywhere.
![folder setup](https://cloud.githubusercontent.com/assets/14055146/11080403/16e9a86e-880b-11e5-9451-20cfd3a9a068.PNG)

**Comment by shirakaba** [comment]
We've reverted to a non-SDL_Image-dependent build so it now works again.
