### ISSUE TITLE
Creating a basic menu screen would be good.

### ISSUE THREAD

**Issue by Syreniac** [Syreniac/verdant-octo-spork#23]
Making a basic menu screen is a little tricky, but goes a long way towards making our program seem more polished.

Start by writing a function in init.c (and add the topline to init.h) that will loop and check events until someone presses a key, and returns once they've pressed it. Then add that function call to the main() function in main.c, in between initialise() and gameStart().

**Comment by Syreniac** [comment]
If you are lucky enough to get some time at the weekend, have a look at this. The event loop will be similar to the one at the end of gameLoop, so you can get some inspiration from there. We don't need a menu layout yet, just a pause and a place in the code to expand on later.

**Comment by chinghp** [comment]
A draft welcome screen has been created.

**Comment by shirakaba** [comment]
Welcome screen finished ^^
