### ISSUE TITLE
Objects don't rotate to reflect their actual heading.

### ISSUE THREAD

**Issue by Syreniac** [Syreniac/verdant-octo-spork#28]
Now that we have a render based system rather than a surface/blit system, we can do some extra magic to make various transformations of our images happen.

The most obvious is to change SDL_RenderCopy() to SDL_RenderCopyEx() in the graphics function that draws all our game objects, and giving it an extra argument representing the desired rotation.

**Comment by shirakaba** [comment]
I've implemented SDL_RenderCopyEx, but something serious seems to be lost in the conversion of angle (in radians) from `gameObjectData->programmableWorkers[i].heading` to that of SDL_RenderCopyEx's expected input in degrees. It rotates fairly randomly; I can't figure out why.

**Comment by shirakaba** [comment]
Thanks to Matt for changing the angle from `gameObjectData->programmableWorkers[i].heading * RADIANSTODEGREES` to `DEGREESINCIRCLE-gameObjectData->programmableWorkers[i].heading * RADIANSTODEGREES`, the angle matches perfectly! Feature complete :)
