### ISSUE TITLE
Currently no modules have any test cases

### ISSUE THREAD

**Issue by Syreniac** [Syreniac/verdant-octo-spork#29]
Ian probably wants us to look at putting some test cases into our code so that we can be sure changes we make don't break anything.

**Comment by shirakaba** [comment]
Test cases added for loadBMP and fopen on commit e18d7cc (23rd Nov).

**Comment by shirakaba** [comment]
I have now integrated the first of the unit tests, and have set up the makefile so that the executable for those tests runs! (Mac-only for now; will edit the makefile for Linux lab and Windows support later)
