### ISSUE TITLE
resourceNodes (flowers) should have constant height and width (20,20) but they keep getting set to zero

### ISSUE THREAD

**Issue by aodl** [Syreniac/verdant-octo-spork#30]
I have even explicitly set there rect.w and rect.h values to 20 when they are created (this shouldn't need to be done because they get these values from the image that is loaded). But somewhere they get set to zero. This might be a similar problem to the bee, which kept getting crazy values for height and width because they were getting clipped when they flew off the screen. This was solved by sending a copy of their rect to the rendering function and not their actual rect (so that clipping changes were not permanent). A similar thing might need to be done for flowers.

**Comment by shirakaba** [comment]
Haven't checked the result yet, but I wonder if it's this. In game_objects.c, rect.x is expecting an int, but we're passing it a float at:

```
resourceNode.rect.x = parentSpawner->xPosition + generateRandomCoordOffset(parentSpawner->spawnRadius) - X_SIZE_OF_NODE/2;
  resourceNode.rect.y = parentSpawner->yPosition + generateRandomCoordOffset(parentSpawner->spawnRadius) - Y_SIZE_OF_NODE/2;
```

I've cast the result of the equation as an int on my end just to resolve the mismatch in types, but I haven't investigated whether that gets us the right values, nor whether it fixes the problem yet. Will commit later.

**Comment by shirakaba** [comment]
![screen shot 2015-11-22 at 22 39 53](https://cloud.githubusercontent.com/assets/14055146/11326766/ff94c082-9169-11e5-8784-abdf8398c69b.png)
My debugger says that, at least for any nodes that have already been initialised, and at least for my current build of the program, the rect.w and rect.h values of the resourceNodes themselves are 20, and the collisionRect of the ResourceNodeSpawner is 200*200. For those that are uninitialised, the rect.w and rect.h values of the resourceNodes are random numbers (and the rect.w and rect.h of their spawner's collisionRect is 0,0).

Are you perhaps looking at uninitialised resourceNodeSpawner collisionRects?

**Comment by aodl** [comment]
Yes! i was looking at uninitialized resourceNodeSpawners! woops!
