### ISSUE TITLE
Bee and flower graphics have loose pixels around them after transparency added.

### ISSUE THREAD

**Issue by Syreniac** [Syreniac/verdant-octo-spork#4]
Currently, bee and flower graphics have loose pixels around them after adding transparency through the SDL_SetColorKey function. This should not be happening.

**Comment by shirakaba** [comment]
Have added PNG support in my branch; will have full transparency support once merged to origin, but need to make sure such .pngs are in the assets folder for use.

**Comment by shirakaba** [comment]
PNGs for all images in use are now available in assets folder on my branch. Migrated from SDL_LoadBMP() to IMG_Load() from "SDL_image.h".
