### ISSUE TITLE
Pause label doesn't toggle correctly

### ISSUE THREAD

**Issue by aodl** [Syreniac/verdant-octo-spork#56]
Pause label doesn't appear sometimes when pausing, but then appears when unpausing

**Comment by aodl** [comment]
This issue runs deeper in that some bees are paused sometimes while other are not

**Comment by Syreniac** [comment]
This should be fixed (again) in my latest commit. It keeps breaking though, I'll have to look into it in a bit more detail at some point.

**Comment by Syreniac** [comment]
This should be fixed in my next commit. Hopefully now I've done a bit of work with the UI backend, it'll stay working this time.
