### ISSUE TITLE
Automatic return to center of map functionality (now that the world is so big)

### ISSUE THREAD

**Issue by aodl** [Syreniac/verdant-octo-spork#57]

**Comment by aodl** [comment]
Also I guess the minimap needs to be updated so that the trees and resourceNodes in particular are still visible on the map (instead of being to small to be rendered which is what i guess is happening(

**Comment by Syreniac** [comment]
We could bind the Home key, or maybe Space?

Space seems a little too "important" for that but those are probably the best two options. If someone writes a function to center the camera on the hive, then I think we'll be able to hook it in easily.

**Comment by Syreniac** [comment]
I've bound it to H in my next commit.
