### ISSUE TITLE
A better bee hive image is needed.

### ISSUE THREAD

**Issue by Syreniac** [Syreniac/verdant-octo-spork#8]
I've grabbed a clip art one, but I hate the art style. Does anyone more graphically talented want to make one?

**Comment by shirakaba** [comment]
Heya - just about to go to bed, but here is a placeholder from
Banjo-Kazooie that I can work on tomorrow. Currently it's a .png, but I can
convert it to a .bmp with a green background to have the green channel act
as the alpha channel.

http://www.models-resource.com/resources/sheet_icons/9/8585.png

**Comment by shirakaba** [comment]
I've added the bee hive as a png, with png support, to my branch.
